
FROM php:8.2-apache

RUN docker-php-ext-install pdo_mysql \
  && a2enmod rewrite \
  && apt-get update \
  && apt-get install -y --no-install-recommends curl \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

COPY . /var/www/html

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80